name: Publish MFE

on:
  workflow_call:
    inputs:
      firebase_project:
        required: true
        type: string
    secrets:
      package_token:
        required: true
      firebase_auth:
        required: true
      firebase_token:
        required: true

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Create .npmrc file
      env:
        package_token: ${{ secrets.package_token }}
      run: |
        touch .npmrc
        echo registry=https://registry.npmjs.com/ >> .npmrc
        echo @jw-project:registry=https://npm.pkg.github.com/ >> .npmrc
        echo //npm.pkg.github.com/:_authToken=$package_token >> .npmrc
        cat .npmrc
      shell: bash
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g firebase-tools
    - run: npm ci
    - run: npm run build
    - run: npm run publish-mfe -- --firebaseAuth ${{ secrets.firebase_auth }}
    - run: firebase use ${{ inputs.firebase_project }}
    - run: firebase target:apply hosting static ${{ inputs.firebase_project }}-static
    - run: firebase deploy --only hosting:static --token ${{ secrets.firebase_token }} -P ${{ inputs.firebase_project }}
